version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8

jobs:
  test-3.6: &template
    docker:
      - image: j5api/ci:3.6
    steps:
      - checkout
      - run:
          name: Merge with parent branch
          command: |
            if [ -n "${CIRCLE_PULL_REQUEST:-}" ]; then
              git config user.name "dummy"
              git config user.email "dummy@example.org"
              parent_branch=$(circleci-branch)
              git fetch origin $parent_branch
              git merge --squash origin/$parent_branch
            fi
      - restore_cache:
          keys:
            - pip-packages-{{ .Branch }}-{{ checksum "poetry.lock" }}
            - pip-packages-{{ .Branch }}-
            - pip-packages-
      - run: poetry install -E vision
      - run: make lint
      - run: make type
      - run: make test
      - run: make -C docs html
      - store_artifacts:
          path: docs/build/html/
          destination: docs
      - save_cache:
          paths:
            - /root/.cache/pypoetry/virtualenvs
          key: pip-packages-{{ .Branch }}-{{ checksum "poetry.lock" }}
  test-3.7:
    <<: *template
    docker:
      - image: j5api/ci:3.7
  test-3.8:
    <<: *template
    docker:
      - image: j5api/ci:3.8
